"""empty message

Revision ID: 614a50f12a58
Revises: 97efa3d440d9
Create Date: 2020-12-28 11:59:04.108811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '614a50f12a58'
down_revision = '97efa3d440d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('post', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
