"""empty message

Revision ID: 822ec12cfb06
Revises: f6d2e982b1ed
Create Date: 2020-12-22 16:22:45.469613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822ec12cfb06'
down_revision = 'f6d2e982b1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'link')
    op.drop_column('tag', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('post_id', sa.INTEGER(), nullable=True))
    op.add_column('tag', sa.Column('link', sa.VARCHAR(length=1000), nullable=True))
    op.create_foreign_key(None, 'tag', 'post', ['post_id'], ['id'])
    op.drop_table('post_tag')
    # ### end Alembic commands ###
