"""3. migration.

Revision ID: a54f962decf4
Revises: d38a1062238f
Create Date: 2020-12-20 13:36:57.451217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54f962decf4'
down_revision = 'd38a1062238f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('author', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
