"""2. migration.

Revision ID: d38a1062238f
Revises: f516cfd88ba3
Create Date: 2020-12-19 18:53:14.738970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38a1062238f'
down_revision = 'f516cfd88ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blog_post', sa.Column('tags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'tags')
    op.drop_table('tag')
    # ### end Alembic commands ###
