"""empty message

Revision ID: f0205419a9a8
Revises: ad0c258e59b2
Create Date: 2020-12-20 20:55:58.362433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0205419a9a8'
down_revision = 'ad0c258e59b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('link', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
