"""empty message

Revision ID: f6d2e982b1ed
Revises: f0205419a9a8
Create Date: 2020-12-21 16:49:50.813165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d2e982b1ed'
down_revision = 'f0205419a9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tagsString', sa.String(length=200), nullable=True))
    op.drop_column('tag', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('link', sa.VARCHAR(length=1000), nullable=True))
    op.drop_column('post', 'tagsString')
    # ### end Alembic commands ###
